json generation fully implemented
Phoenix-Spark/hub pull request #14
Opened 2023-09-07 21:47 UTC by kyle-koch

press the button Kronk!

2023-09-07 22:16 UTC, jmidd2 commented on server/src/Routes/Json.ts
You left some unneeded words in the console.

2023-09-07 22:17 UTC, jmidd2 commented
The functionality is all good. The location and name of files needs to be moved around though. The exportDbToJson that you created is a service it's a part of our business logic. Business logic and services live in the Services folder.

2023-09-07 22:23 UTC, jmidd2 requested changes
The functionality is all good. The location and name of files needs to be moved around though. The exportDbToJson that you created is a service it's a part of our business logic. Business logic and services live in the Services folder. the Json.ts routes file has some unneeded words in it as well.

2023-09-07 22:51 UTC, kyle-koch commented
Hopefully this is better 😅

2023-09-08 16:11 UTC, jmidd2 approved these changes

2023-09-08 16:12 UTC, merged